name: pansy_ui
description: A pretty GUI kit for oneLab projects.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  native_device_orientation: ^0.3.0
  flutter_bloc: ^3.2.0
  shared_preferences: ^0.5.6+1
