name: pansy_ui
description: A pretty GUI kit for oneLab projects.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # design
  ubuntu_font_flutter: ^0.0.1
  flare_flutter: ^2.0.1
  transparent_image: ^1.0.0

  # localizations
  devicelocale: ^0.2.2

  # bloc
  rxdart: ^0.23.1
  provider: ^4.0.4

  # db
  shared_preferences: ^0.5.6+2

  # compare
  equatable: ^1.1.0
